linters:
- import:
    packages: ['meanfield']
- namespace:
    filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '- tools/*',
                 '+ *.py', '+ *.pyx']
- pylint:
- pycodestyle:
- pydocstyle:
    config: .pycodestylerc
- whitespace:
