package:
  version: "{{ PROJECT_VERSION }}"
  name: 'meanfield'

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  #script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - python
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
    - libxc >=3.0.0
    - gcc     # [ not win ]
  run:
    - python
    - numpy
    - nose
    - libxc
    - libgcc  # [ not win ]

about:
  description: HORTON module for SCF and HF/DFT methods 
  home: https://github.com/theochem/meanfield
  license: GPLv3

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
