package:
  version: "{{ PROJECT_VERSION }}"
  name: 'meanfield'

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python ={{ MYCONDAPY }}
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
    - libxc >=3 
  run:
    - python
    - numpy
    - nose
    - libxc
    - scipy
    - old_grids
    - gbasis
    - matplotlib
test:
  requires:
    - nose
  commands:
    - conda inspect linkages meanfield
    - nosetests -v --detailed-errors meanfield

about:
  description: HORTON module for SCF and HF/DFT methods 
  home: https://github.com/theochem/meanfield
  license: GPLv3

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
